/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BeeswaxService_H
#define BeeswaxService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "beeswax_types.h"

namespace beeswax {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class BeeswaxServiceIf {
 public:
  virtual ~BeeswaxServiceIf() {}

  /**
   * Submit a query and return a handle (QueryHandle). The query runs asynchronously.
   * 
   * @param query
   */
  virtual void query(QueryHandle& _return, const Query& query) = 0;

  /**
   * run a query synchronously and return a handle (QueryHandle).
   * 
   * @param query
   * @param clientCtx
   */
  virtual void executeAndWait(QueryHandle& _return, const Query& query, const LogContextId& clientCtx) = 0;

  /**
   * Get the query plan for a query.
   * 
   * @param query
   */
  virtual void explain(QueryExplanation& _return, const Query& query) = 0;

  /**
   * Get the results of a query. This is non-blocking. Caller should check
   * Results.ready to determine if the results are in yet. The call requests
   * the batch size of fetch.
   * 
   * @param query_id
   * @param start_over
   * @param fetch_size
   */
  virtual void fetch(Results& _return, const QueryHandle& query_id, const bool start_over, const int32_t fetch_size) = 0;

  /**
   * Get the state of the query
   * 
   * @param handle
   */
  virtual QueryState::type get_state(const QueryHandle& handle) = 0;

  /**
   * Get the result metadata
   * 
   * @param handle
   */
  virtual void get_results_metadata(ResultsMetadata& _return, const QueryHandle& handle) = 0;

  /**
   * Used to test connection to server.  A "noop" command.
   * 
   * @param s
   */
  virtual void echo(std::string& _return, const std::string& s) = 0;

  /**
   * Returns a string representation of the configuration object being used.
   * Handy for debugging.
   */
  virtual void dump_config(std::string& _return) = 0;

  /**
   * Get the log messages related to the given context.
   * 
   * @param context
   */
  virtual void get_log(std::string& _return, const LogContextId& context) = 0;
  virtual void get_default_configuration(std::vector<ConfigVariable> & _return, const bool include_hadoop) = 0;
  virtual void close(const QueryHandle& handle) = 0;
  virtual void clean(const LogContextId& log_context) = 0;
};

class BeeswaxServiceIfFactory {
 public:
  typedef BeeswaxServiceIf Handler;

  virtual ~BeeswaxServiceIfFactory() {}

  virtual BeeswaxServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(BeeswaxServiceIf* /* handler */) = 0;
};

class BeeswaxServiceIfSingletonFactory : virtual public BeeswaxServiceIfFactory {
 public:
  BeeswaxServiceIfSingletonFactory(const boost::shared_ptr<BeeswaxServiceIf>& iface) : iface_(iface) {}
  virtual ~BeeswaxServiceIfSingletonFactory() {}

  virtual BeeswaxServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(BeeswaxServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<BeeswaxServiceIf> iface_;
};

class BeeswaxServiceNull : virtual public BeeswaxServiceIf {
 public:
  virtual ~BeeswaxServiceNull() {}
  void query(QueryHandle& /* _return */, const Query& /* query */) {
    return;
  }
  void executeAndWait(QueryHandle& /* _return */, const Query& /* query */, const LogContextId& /* clientCtx */) {
    return;
  }
  void explain(QueryExplanation& /* _return */, const Query& /* query */) {
    return;
  }
  void fetch(Results& /* _return */, const QueryHandle& /* query_id */, const bool /* start_over */, const int32_t /* fetch_size */) {
    return;
  }
  QueryState::type get_state(const QueryHandle& /* handle */) {
    QueryState::type _return = (QueryState::type)0;
    return _return;
  }
  void get_results_metadata(ResultsMetadata& /* _return */, const QueryHandle& /* handle */) {
    return;
  }
  void echo(std::string& /* _return */, const std::string& /* s */) {
    return;
  }
  void dump_config(std::string& /* _return */) {
    return;
  }
  void get_log(std::string& /* _return */, const LogContextId& /* context */) {
    return;
  }
  void get_default_configuration(std::vector<ConfigVariable> & /* _return */, const bool /* include_hadoop */) {
    return;
  }
  void close(const QueryHandle& /* handle */) {
    return;
  }
  void clean(const LogContextId& /* log_context */) {
    return;
  }
};

typedef struct _BeeswaxService_query_args__isset {
  _BeeswaxService_query_args__isset() : query(false) {}
  bool query :1;
} _BeeswaxService_query_args__isset;

class BeeswaxService_query_args {
 public:

  BeeswaxService_query_args(const BeeswaxService_query_args&);
  BeeswaxService_query_args& operator=(const BeeswaxService_query_args&);
  BeeswaxService_query_args() {
  }

  virtual ~BeeswaxService_query_args() throw();
  Query query;

  _BeeswaxService_query_args__isset __isset;

  void __set_query(const Query& val);

  bool operator == (const BeeswaxService_query_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_query_pargs {
 public:


  virtual ~BeeswaxService_query_pargs() throw();
  const Query* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_query_result__isset {
  _BeeswaxService_query_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_query_result__isset;

class BeeswaxService_query_result {
 public:

  BeeswaxService_query_result(const BeeswaxService_query_result&);
  BeeswaxService_query_result& operator=(const BeeswaxService_query_result&);
  BeeswaxService_query_result() {
  }

  virtual ~BeeswaxService_query_result() throw();
  QueryHandle success;
  BeeswaxException error;

  _BeeswaxService_query_result__isset __isset;

  void __set_success(const QueryHandle& val);

  void __set_error(const BeeswaxException& val);

  bool operator == (const BeeswaxService_query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_query_presult__isset {
  _BeeswaxService_query_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_query_presult__isset;

class BeeswaxService_query_presult {
 public:


  virtual ~BeeswaxService_query_presult() throw();
  QueryHandle* success;
  BeeswaxException error;

  _BeeswaxService_query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_executeAndWait_args__isset {
  _BeeswaxService_executeAndWait_args__isset() : query(false), clientCtx(false) {}
  bool query :1;
  bool clientCtx :1;
} _BeeswaxService_executeAndWait_args__isset;

class BeeswaxService_executeAndWait_args {
 public:

  BeeswaxService_executeAndWait_args(const BeeswaxService_executeAndWait_args&);
  BeeswaxService_executeAndWait_args& operator=(const BeeswaxService_executeAndWait_args&);
  BeeswaxService_executeAndWait_args() : clientCtx() {
  }

  virtual ~BeeswaxService_executeAndWait_args() throw();
  Query query;
  LogContextId clientCtx;

  _BeeswaxService_executeAndWait_args__isset __isset;

  void __set_query(const Query& val);

  void __set_clientCtx(const LogContextId& val);

  bool operator == (const BeeswaxService_executeAndWait_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    if (!(clientCtx == rhs.clientCtx))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_executeAndWait_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_executeAndWait_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_executeAndWait_pargs {
 public:


  virtual ~BeeswaxService_executeAndWait_pargs() throw();
  const Query* query;
  const LogContextId* clientCtx;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_executeAndWait_result__isset {
  _BeeswaxService_executeAndWait_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_executeAndWait_result__isset;

class BeeswaxService_executeAndWait_result {
 public:

  BeeswaxService_executeAndWait_result(const BeeswaxService_executeAndWait_result&);
  BeeswaxService_executeAndWait_result& operator=(const BeeswaxService_executeAndWait_result&);
  BeeswaxService_executeAndWait_result() {
  }

  virtual ~BeeswaxService_executeAndWait_result() throw();
  QueryHandle success;
  BeeswaxException error;

  _BeeswaxService_executeAndWait_result__isset __isset;

  void __set_success(const QueryHandle& val);

  void __set_error(const BeeswaxException& val);

  bool operator == (const BeeswaxService_executeAndWait_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_executeAndWait_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_executeAndWait_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_executeAndWait_presult__isset {
  _BeeswaxService_executeAndWait_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_executeAndWait_presult__isset;

class BeeswaxService_executeAndWait_presult {
 public:


  virtual ~BeeswaxService_executeAndWait_presult() throw();
  QueryHandle* success;
  BeeswaxException error;

  _BeeswaxService_executeAndWait_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_explain_args__isset {
  _BeeswaxService_explain_args__isset() : query(false) {}
  bool query :1;
} _BeeswaxService_explain_args__isset;

class BeeswaxService_explain_args {
 public:

  BeeswaxService_explain_args(const BeeswaxService_explain_args&);
  BeeswaxService_explain_args& operator=(const BeeswaxService_explain_args&);
  BeeswaxService_explain_args() {
  }

  virtual ~BeeswaxService_explain_args() throw();
  Query query;

  _BeeswaxService_explain_args__isset __isset;

  void __set_query(const Query& val);

  bool operator == (const BeeswaxService_explain_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_explain_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_explain_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_explain_pargs {
 public:


  virtual ~BeeswaxService_explain_pargs() throw();
  const Query* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_explain_result__isset {
  _BeeswaxService_explain_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_explain_result__isset;

class BeeswaxService_explain_result {
 public:

  BeeswaxService_explain_result(const BeeswaxService_explain_result&);
  BeeswaxService_explain_result& operator=(const BeeswaxService_explain_result&);
  BeeswaxService_explain_result() {
  }

  virtual ~BeeswaxService_explain_result() throw();
  QueryExplanation success;
  BeeswaxException error;

  _BeeswaxService_explain_result__isset __isset;

  void __set_success(const QueryExplanation& val);

  void __set_error(const BeeswaxException& val);

  bool operator == (const BeeswaxService_explain_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_explain_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_explain_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_explain_presult__isset {
  _BeeswaxService_explain_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_explain_presult__isset;

class BeeswaxService_explain_presult {
 public:


  virtual ~BeeswaxService_explain_presult() throw();
  QueryExplanation* success;
  BeeswaxException error;

  _BeeswaxService_explain_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_fetch_args__isset {
  _BeeswaxService_fetch_args__isset() : query_id(false), start_over(false), fetch_size(true) {}
  bool query_id :1;
  bool start_over :1;
  bool fetch_size :1;
} _BeeswaxService_fetch_args__isset;

class BeeswaxService_fetch_args {
 public:

  BeeswaxService_fetch_args(const BeeswaxService_fetch_args&);
  BeeswaxService_fetch_args& operator=(const BeeswaxService_fetch_args&);
  BeeswaxService_fetch_args() : start_over(0), fetch_size(-1) {
  }

  virtual ~BeeswaxService_fetch_args() throw();
  QueryHandle query_id;
  bool start_over;
  int32_t fetch_size;

  _BeeswaxService_fetch_args__isset __isset;

  void __set_query_id(const QueryHandle& val);

  void __set_start_over(const bool val);

  void __set_fetch_size(const int32_t val);

  bool operator == (const BeeswaxService_fetch_args & rhs) const
  {
    if (!(query_id == rhs.query_id))
      return false;
    if (!(start_over == rhs.start_over))
      return false;
    if (!(fetch_size == rhs.fetch_size))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_fetch_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_fetch_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_fetch_pargs {
 public:


  virtual ~BeeswaxService_fetch_pargs() throw();
  const QueryHandle* query_id;
  const bool* start_over;
  const int32_t* fetch_size;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_fetch_result__isset {
  _BeeswaxService_fetch_result__isset() : success(false), error(false), error2(false) {}
  bool success :1;
  bool error :1;
  bool error2 :1;
} _BeeswaxService_fetch_result__isset;

class BeeswaxService_fetch_result {
 public:

  BeeswaxService_fetch_result(const BeeswaxService_fetch_result&);
  BeeswaxService_fetch_result& operator=(const BeeswaxService_fetch_result&);
  BeeswaxService_fetch_result() {
  }

  virtual ~BeeswaxService_fetch_result() throw();
  Results success;
  QueryNotFoundException error;
  BeeswaxException error2;

  _BeeswaxService_fetch_result__isset __isset;

  void __set_success(const Results& val);

  void __set_error(const QueryNotFoundException& val);

  void __set_error2(const BeeswaxException& val);

  bool operator == (const BeeswaxService_fetch_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    if (!(error2 == rhs.error2))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_fetch_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_fetch_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_fetch_presult__isset {
  _BeeswaxService_fetch_presult__isset() : success(false), error(false), error2(false) {}
  bool success :1;
  bool error :1;
  bool error2 :1;
} _BeeswaxService_fetch_presult__isset;

class BeeswaxService_fetch_presult {
 public:


  virtual ~BeeswaxService_fetch_presult() throw();
  Results* success;
  QueryNotFoundException error;
  BeeswaxException error2;

  _BeeswaxService_fetch_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_get_state_args__isset {
  _BeeswaxService_get_state_args__isset() : handle(false) {}
  bool handle :1;
} _BeeswaxService_get_state_args__isset;

class BeeswaxService_get_state_args {
 public:

  BeeswaxService_get_state_args(const BeeswaxService_get_state_args&);
  BeeswaxService_get_state_args& operator=(const BeeswaxService_get_state_args&);
  BeeswaxService_get_state_args() {
  }

  virtual ~BeeswaxService_get_state_args() throw();
  QueryHandle handle;

  _BeeswaxService_get_state_args__isset __isset;

  void __set_handle(const QueryHandle& val);

  bool operator == (const BeeswaxService_get_state_args & rhs) const
  {
    if (!(handle == rhs.handle))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_state_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_state_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_get_state_pargs {
 public:


  virtual ~BeeswaxService_get_state_pargs() throw();
  const QueryHandle* handle;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_state_result__isset {
  _BeeswaxService_get_state_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_state_result__isset;

class BeeswaxService_get_state_result {
 public:

  BeeswaxService_get_state_result(const BeeswaxService_get_state_result&);
  BeeswaxService_get_state_result& operator=(const BeeswaxService_get_state_result&);
  BeeswaxService_get_state_result() : success((QueryState::type)0) {
  }

  virtual ~BeeswaxService_get_state_result() throw();
  QueryState::type success;
  QueryNotFoundException error;

  _BeeswaxService_get_state_result__isset __isset;

  void __set_success(const QueryState::type val);

  void __set_error(const QueryNotFoundException& val);

  bool operator == (const BeeswaxService_get_state_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_state_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_state_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_state_presult__isset {
  _BeeswaxService_get_state_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_state_presult__isset;

class BeeswaxService_get_state_presult {
 public:


  virtual ~BeeswaxService_get_state_presult() throw();
  QueryState::type* success;
  QueryNotFoundException error;

  _BeeswaxService_get_state_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_get_results_metadata_args__isset {
  _BeeswaxService_get_results_metadata_args__isset() : handle(false) {}
  bool handle :1;
} _BeeswaxService_get_results_metadata_args__isset;

class BeeswaxService_get_results_metadata_args {
 public:

  BeeswaxService_get_results_metadata_args(const BeeswaxService_get_results_metadata_args&);
  BeeswaxService_get_results_metadata_args& operator=(const BeeswaxService_get_results_metadata_args&);
  BeeswaxService_get_results_metadata_args() {
  }

  virtual ~BeeswaxService_get_results_metadata_args() throw();
  QueryHandle handle;

  _BeeswaxService_get_results_metadata_args__isset __isset;

  void __set_handle(const QueryHandle& val);

  bool operator == (const BeeswaxService_get_results_metadata_args & rhs) const
  {
    if (!(handle == rhs.handle))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_results_metadata_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_results_metadata_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_get_results_metadata_pargs {
 public:


  virtual ~BeeswaxService_get_results_metadata_pargs() throw();
  const QueryHandle* handle;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_results_metadata_result__isset {
  _BeeswaxService_get_results_metadata_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_results_metadata_result__isset;

class BeeswaxService_get_results_metadata_result {
 public:

  BeeswaxService_get_results_metadata_result(const BeeswaxService_get_results_metadata_result&);
  BeeswaxService_get_results_metadata_result& operator=(const BeeswaxService_get_results_metadata_result&);
  BeeswaxService_get_results_metadata_result() {
  }

  virtual ~BeeswaxService_get_results_metadata_result() throw();
  ResultsMetadata success;
  QueryNotFoundException error;

  _BeeswaxService_get_results_metadata_result__isset __isset;

  void __set_success(const ResultsMetadata& val);

  void __set_error(const QueryNotFoundException& val);

  bool operator == (const BeeswaxService_get_results_metadata_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_results_metadata_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_results_metadata_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_results_metadata_presult__isset {
  _BeeswaxService_get_results_metadata_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_results_metadata_presult__isset;

class BeeswaxService_get_results_metadata_presult {
 public:


  virtual ~BeeswaxService_get_results_metadata_presult() throw();
  ResultsMetadata* success;
  QueryNotFoundException error;

  _BeeswaxService_get_results_metadata_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_echo_args__isset {
  _BeeswaxService_echo_args__isset() : s(false) {}
  bool s :1;
} _BeeswaxService_echo_args__isset;

class BeeswaxService_echo_args {
 public:

  BeeswaxService_echo_args(const BeeswaxService_echo_args&);
  BeeswaxService_echo_args& operator=(const BeeswaxService_echo_args&);
  BeeswaxService_echo_args() : s() {
  }

  virtual ~BeeswaxService_echo_args() throw();
  std::string s;

  _BeeswaxService_echo_args__isset __isset;

  void __set_s(const std::string& val);

  bool operator == (const BeeswaxService_echo_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_echo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_echo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_echo_pargs {
 public:


  virtual ~BeeswaxService_echo_pargs() throw();
  const std::string* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_echo_result__isset {
  _BeeswaxService_echo_result__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_echo_result__isset;

class BeeswaxService_echo_result {
 public:

  BeeswaxService_echo_result(const BeeswaxService_echo_result&);
  BeeswaxService_echo_result& operator=(const BeeswaxService_echo_result&);
  BeeswaxService_echo_result() : success() {
  }

  virtual ~BeeswaxService_echo_result() throw();
  std::string success;

  _BeeswaxService_echo_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const BeeswaxService_echo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_echo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_echo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_echo_presult__isset {
  _BeeswaxService_echo_presult__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_echo_presult__isset;

class BeeswaxService_echo_presult {
 public:


  virtual ~BeeswaxService_echo_presult() throw();
  std::string* success;

  _BeeswaxService_echo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class BeeswaxService_dump_config_args {
 public:

  BeeswaxService_dump_config_args(const BeeswaxService_dump_config_args&);
  BeeswaxService_dump_config_args& operator=(const BeeswaxService_dump_config_args&);
  BeeswaxService_dump_config_args() {
  }

  virtual ~BeeswaxService_dump_config_args() throw();

  bool operator == (const BeeswaxService_dump_config_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const BeeswaxService_dump_config_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_dump_config_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_dump_config_pargs {
 public:


  virtual ~BeeswaxService_dump_config_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_dump_config_result__isset {
  _BeeswaxService_dump_config_result__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_dump_config_result__isset;

class BeeswaxService_dump_config_result {
 public:

  BeeswaxService_dump_config_result(const BeeswaxService_dump_config_result&);
  BeeswaxService_dump_config_result& operator=(const BeeswaxService_dump_config_result&);
  BeeswaxService_dump_config_result() : success() {
  }

  virtual ~BeeswaxService_dump_config_result() throw();
  std::string success;

  _BeeswaxService_dump_config_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const BeeswaxService_dump_config_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_dump_config_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_dump_config_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_dump_config_presult__isset {
  _BeeswaxService_dump_config_presult__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_dump_config_presult__isset;

class BeeswaxService_dump_config_presult {
 public:


  virtual ~BeeswaxService_dump_config_presult() throw();
  std::string* success;

  _BeeswaxService_dump_config_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_get_log_args__isset {
  _BeeswaxService_get_log_args__isset() : context(false) {}
  bool context :1;
} _BeeswaxService_get_log_args__isset;

class BeeswaxService_get_log_args {
 public:

  BeeswaxService_get_log_args(const BeeswaxService_get_log_args&);
  BeeswaxService_get_log_args& operator=(const BeeswaxService_get_log_args&);
  BeeswaxService_get_log_args() : context() {
  }

  virtual ~BeeswaxService_get_log_args() throw();
  LogContextId context;

  _BeeswaxService_get_log_args__isset __isset;

  void __set_context(const LogContextId& val);

  bool operator == (const BeeswaxService_get_log_args & rhs) const
  {
    if (!(context == rhs.context))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_log_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_log_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_get_log_pargs {
 public:


  virtual ~BeeswaxService_get_log_pargs() throw();
  const LogContextId* context;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_log_result__isset {
  _BeeswaxService_get_log_result__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_log_result__isset;

class BeeswaxService_get_log_result {
 public:

  BeeswaxService_get_log_result(const BeeswaxService_get_log_result&);
  BeeswaxService_get_log_result& operator=(const BeeswaxService_get_log_result&);
  BeeswaxService_get_log_result() : success() {
  }

  virtual ~BeeswaxService_get_log_result() throw();
  std::string success;
  QueryNotFoundException error;

  _BeeswaxService_get_log_result__isset __isset;

  void __set_success(const std::string& val);

  void __set_error(const QueryNotFoundException& val);

  bool operator == (const BeeswaxService_get_log_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_log_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_log_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_log_presult__isset {
  _BeeswaxService_get_log_presult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _BeeswaxService_get_log_presult__isset;

class BeeswaxService_get_log_presult {
 public:


  virtual ~BeeswaxService_get_log_presult() throw();
  std::string* success;
  QueryNotFoundException error;

  _BeeswaxService_get_log_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_get_default_configuration_args__isset {
  _BeeswaxService_get_default_configuration_args__isset() : include_hadoop(false) {}
  bool include_hadoop :1;
} _BeeswaxService_get_default_configuration_args__isset;

class BeeswaxService_get_default_configuration_args {
 public:

  BeeswaxService_get_default_configuration_args(const BeeswaxService_get_default_configuration_args&);
  BeeswaxService_get_default_configuration_args& operator=(const BeeswaxService_get_default_configuration_args&);
  BeeswaxService_get_default_configuration_args() : include_hadoop(0) {
  }

  virtual ~BeeswaxService_get_default_configuration_args() throw();
  bool include_hadoop;

  _BeeswaxService_get_default_configuration_args__isset __isset;

  void __set_include_hadoop(const bool val);

  bool operator == (const BeeswaxService_get_default_configuration_args & rhs) const
  {
    if (!(include_hadoop == rhs.include_hadoop))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_default_configuration_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_default_configuration_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_get_default_configuration_pargs {
 public:


  virtual ~BeeswaxService_get_default_configuration_pargs() throw();
  const bool* include_hadoop;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_default_configuration_result__isset {
  _BeeswaxService_get_default_configuration_result__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_get_default_configuration_result__isset;

class BeeswaxService_get_default_configuration_result {
 public:

  BeeswaxService_get_default_configuration_result(const BeeswaxService_get_default_configuration_result&);
  BeeswaxService_get_default_configuration_result& operator=(const BeeswaxService_get_default_configuration_result&);
  BeeswaxService_get_default_configuration_result() {
  }

  virtual ~BeeswaxService_get_default_configuration_result() throw();
  std::vector<ConfigVariable>  success;

  _BeeswaxService_get_default_configuration_result__isset __isset;

  void __set_success(const std::vector<ConfigVariable> & val);

  bool operator == (const BeeswaxService_get_default_configuration_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_get_default_configuration_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_get_default_configuration_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_get_default_configuration_presult__isset {
  _BeeswaxService_get_default_configuration_presult__isset() : success(false) {}
  bool success :1;
} _BeeswaxService_get_default_configuration_presult__isset;

class BeeswaxService_get_default_configuration_presult {
 public:


  virtual ~BeeswaxService_get_default_configuration_presult() throw();
  std::vector<ConfigVariable> * success;

  _BeeswaxService_get_default_configuration_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_close_args__isset {
  _BeeswaxService_close_args__isset() : handle(false) {}
  bool handle :1;
} _BeeswaxService_close_args__isset;

class BeeswaxService_close_args {
 public:

  BeeswaxService_close_args(const BeeswaxService_close_args&);
  BeeswaxService_close_args& operator=(const BeeswaxService_close_args&);
  BeeswaxService_close_args() {
  }

  virtual ~BeeswaxService_close_args() throw();
  QueryHandle handle;

  _BeeswaxService_close_args__isset __isset;

  void __set_handle(const QueryHandle& val);

  bool operator == (const BeeswaxService_close_args & rhs) const
  {
    if (!(handle == rhs.handle))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_close_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_close_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_close_pargs {
 public:


  virtual ~BeeswaxService_close_pargs() throw();
  const QueryHandle* handle;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_close_result__isset {
  _BeeswaxService_close_result__isset() : error(false), error2(false) {}
  bool error :1;
  bool error2 :1;
} _BeeswaxService_close_result__isset;

class BeeswaxService_close_result {
 public:

  BeeswaxService_close_result(const BeeswaxService_close_result&);
  BeeswaxService_close_result& operator=(const BeeswaxService_close_result&);
  BeeswaxService_close_result() {
  }

  virtual ~BeeswaxService_close_result() throw();
  QueryNotFoundException error;
  BeeswaxException error2;

  _BeeswaxService_close_result__isset __isset;

  void __set_error(const QueryNotFoundException& val);

  void __set_error2(const BeeswaxException& val);

  bool operator == (const BeeswaxService_close_result & rhs) const
  {
    if (!(error == rhs.error))
      return false;
    if (!(error2 == rhs.error2))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_close_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_close_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _BeeswaxService_close_presult__isset {
  _BeeswaxService_close_presult__isset() : error(false), error2(false) {}
  bool error :1;
  bool error2 :1;
} _BeeswaxService_close_presult__isset;

class BeeswaxService_close_presult {
 public:


  virtual ~BeeswaxService_close_presult() throw();
  QueryNotFoundException error;
  BeeswaxException error2;

  _BeeswaxService_close_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _BeeswaxService_clean_args__isset {
  _BeeswaxService_clean_args__isset() : log_context(false) {}
  bool log_context :1;
} _BeeswaxService_clean_args__isset;

class BeeswaxService_clean_args {
 public:

  BeeswaxService_clean_args(const BeeswaxService_clean_args&);
  BeeswaxService_clean_args& operator=(const BeeswaxService_clean_args&);
  BeeswaxService_clean_args() : log_context() {
  }

  virtual ~BeeswaxService_clean_args() throw();
  LogContextId log_context;

  _BeeswaxService_clean_args__isset __isset;

  void __set_log_context(const LogContextId& val);

  bool operator == (const BeeswaxService_clean_args & rhs) const
  {
    if (!(log_context == rhs.log_context))
      return false;
    return true;
  }
  bool operator != (const BeeswaxService_clean_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_clean_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_clean_pargs {
 public:


  virtual ~BeeswaxService_clean_pargs() throw();
  const LogContextId* log_context;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_clean_result {
 public:

  BeeswaxService_clean_result(const BeeswaxService_clean_result&);
  BeeswaxService_clean_result& operator=(const BeeswaxService_clean_result&);
  BeeswaxService_clean_result() {
  }

  virtual ~BeeswaxService_clean_result() throw();

  bool operator == (const BeeswaxService_clean_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const BeeswaxService_clean_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BeeswaxService_clean_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class BeeswaxService_clean_presult {
 public:


  virtual ~BeeswaxService_clean_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class BeeswaxServiceClient : virtual public BeeswaxServiceIf {
 public:
  BeeswaxServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  BeeswaxServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void query(QueryHandle& _return, const Query& query);
  void send_query(const Query& query);
  void recv_query(QueryHandle& _return);
  void executeAndWait(QueryHandle& _return, const Query& query, const LogContextId& clientCtx);
  void send_executeAndWait(const Query& query, const LogContextId& clientCtx);
  void recv_executeAndWait(QueryHandle& _return);
  void explain(QueryExplanation& _return, const Query& query);
  void send_explain(const Query& query);
  void recv_explain(QueryExplanation& _return);
  void fetch(Results& _return, const QueryHandle& query_id, const bool start_over, const int32_t fetch_size);
  void send_fetch(const QueryHandle& query_id, const bool start_over, const int32_t fetch_size);
  void recv_fetch(Results& _return);
  QueryState::type get_state(const QueryHandle& handle);
  void send_get_state(const QueryHandle& handle);
  QueryState::type recv_get_state();
  void get_results_metadata(ResultsMetadata& _return, const QueryHandle& handle);
  void send_get_results_metadata(const QueryHandle& handle);
  void recv_get_results_metadata(ResultsMetadata& _return);
  void echo(std::string& _return, const std::string& s);
  void send_echo(const std::string& s);
  void recv_echo(std::string& _return);
  void dump_config(std::string& _return);
  void send_dump_config();
  void recv_dump_config(std::string& _return);
  void get_log(std::string& _return, const LogContextId& context);
  void send_get_log(const LogContextId& context);
  void recv_get_log(std::string& _return);
  void get_default_configuration(std::vector<ConfigVariable> & _return, const bool include_hadoop);
  void send_get_default_configuration(const bool include_hadoop);
  void recv_get_default_configuration(std::vector<ConfigVariable> & _return);
  void close(const QueryHandle& handle);
  void send_close(const QueryHandle& handle);
  void recv_close();
  void clean(const LogContextId& log_context);
  void send_clean(const LogContextId& log_context);
  void recv_clean();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class BeeswaxServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<BeeswaxServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (BeeswaxServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_executeAndWait(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_explain(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_fetch(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_state(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_results_metadata(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_echo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dump_config(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_log(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_default_configuration(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_close(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_clean(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  BeeswaxServiceProcessor(boost::shared_ptr<BeeswaxServiceIf> iface) :
    iface_(iface) {
    processMap_["query"] = &BeeswaxServiceProcessor::process_query;
    processMap_["executeAndWait"] = &BeeswaxServiceProcessor::process_executeAndWait;
    processMap_["explain"] = &BeeswaxServiceProcessor::process_explain;
    processMap_["fetch"] = &BeeswaxServiceProcessor::process_fetch;
    processMap_["get_state"] = &BeeswaxServiceProcessor::process_get_state;
    processMap_["get_results_metadata"] = &BeeswaxServiceProcessor::process_get_results_metadata;
    processMap_["echo"] = &BeeswaxServiceProcessor::process_echo;
    processMap_["dump_config"] = &BeeswaxServiceProcessor::process_dump_config;
    processMap_["get_log"] = &BeeswaxServiceProcessor::process_get_log;
    processMap_["get_default_configuration"] = &BeeswaxServiceProcessor::process_get_default_configuration;
    processMap_["close"] = &BeeswaxServiceProcessor::process_close;
    processMap_["clean"] = &BeeswaxServiceProcessor::process_clean;
  }

  virtual ~BeeswaxServiceProcessor() {}
};

class BeeswaxServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  BeeswaxServiceProcessorFactory(const ::boost::shared_ptr< BeeswaxServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< BeeswaxServiceIfFactory > handlerFactory_;
};

class BeeswaxServiceMultiface : virtual public BeeswaxServiceIf {
 public:
  BeeswaxServiceMultiface(std::vector<boost::shared_ptr<BeeswaxServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~BeeswaxServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<BeeswaxServiceIf> > ifaces_;
  BeeswaxServiceMultiface() {}
  void add(boost::shared_ptr<BeeswaxServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void query(QueryHandle& _return, const Query& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->query(_return, query);
    }
    ifaces_[i]->query(_return, query);
    return;
  }

  void executeAndWait(QueryHandle& _return, const Query& query, const LogContextId& clientCtx) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->executeAndWait(_return, query, clientCtx);
    }
    ifaces_[i]->executeAndWait(_return, query, clientCtx);
    return;
  }

  void explain(QueryExplanation& _return, const Query& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->explain(_return, query);
    }
    ifaces_[i]->explain(_return, query);
    return;
  }

  void fetch(Results& _return, const QueryHandle& query_id, const bool start_over, const int32_t fetch_size) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->fetch(_return, query_id, start_over, fetch_size);
    }
    ifaces_[i]->fetch(_return, query_id, start_over, fetch_size);
    return;
  }

  QueryState::type get_state(const QueryHandle& handle) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_state(handle);
    }
    return ifaces_[i]->get_state(handle);
  }

  void get_results_metadata(ResultsMetadata& _return, const QueryHandle& handle) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_results_metadata(_return, handle);
    }
    ifaces_[i]->get_results_metadata(_return, handle);
    return;
  }

  void echo(std::string& _return, const std::string& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->echo(_return, s);
    }
    ifaces_[i]->echo(_return, s);
    return;
  }

  void dump_config(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->dump_config(_return);
    }
    ifaces_[i]->dump_config(_return);
    return;
  }

  void get_log(std::string& _return, const LogContextId& context) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_log(_return, context);
    }
    ifaces_[i]->get_log(_return, context);
    return;
  }

  void get_default_configuration(std::vector<ConfigVariable> & _return, const bool include_hadoop) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_default_configuration(_return, include_hadoop);
    }
    ifaces_[i]->get_default_configuration(_return, include_hadoop);
    return;
  }

  void close(const QueryHandle& handle) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->close(handle);
    }
    ifaces_[i]->close(handle);
  }

  void clean(const LogContextId& log_context) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->clean(log_context);
    }
    ifaces_[i]->clean(log_context);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class BeeswaxServiceConcurrentClient : virtual public BeeswaxServiceIf {
 public:
  BeeswaxServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  BeeswaxServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void query(QueryHandle& _return, const Query& query);
  int32_t send_query(const Query& query);
  void recv_query(QueryHandle& _return, const int32_t seqid);
  void executeAndWait(QueryHandle& _return, const Query& query, const LogContextId& clientCtx);
  int32_t send_executeAndWait(const Query& query, const LogContextId& clientCtx);
  void recv_executeAndWait(QueryHandle& _return, const int32_t seqid);
  void explain(QueryExplanation& _return, const Query& query);
  int32_t send_explain(const Query& query);
  void recv_explain(QueryExplanation& _return, const int32_t seqid);
  void fetch(Results& _return, const QueryHandle& query_id, const bool start_over, const int32_t fetch_size);
  int32_t send_fetch(const QueryHandle& query_id, const bool start_over, const int32_t fetch_size);
  void recv_fetch(Results& _return, const int32_t seqid);
  QueryState::type get_state(const QueryHandle& handle);
  int32_t send_get_state(const QueryHandle& handle);
  QueryState::type recv_get_state(const int32_t seqid);
  void get_results_metadata(ResultsMetadata& _return, const QueryHandle& handle);
  int32_t send_get_results_metadata(const QueryHandle& handle);
  void recv_get_results_metadata(ResultsMetadata& _return, const int32_t seqid);
  void echo(std::string& _return, const std::string& s);
  int32_t send_echo(const std::string& s);
  void recv_echo(std::string& _return, const int32_t seqid);
  void dump_config(std::string& _return);
  int32_t send_dump_config();
  void recv_dump_config(std::string& _return, const int32_t seqid);
  void get_log(std::string& _return, const LogContextId& context);
  int32_t send_get_log(const LogContextId& context);
  void recv_get_log(std::string& _return, const int32_t seqid);
  void get_default_configuration(std::vector<ConfigVariable> & _return, const bool include_hadoop);
  int32_t send_get_default_configuration(const bool include_hadoop);
  void recv_get_default_configuration(std::vector<ConfigVariable> & _return, const int32_t seqid);
  void close(const QueryHandle& handle);
  int32_t send_close(const QueryHandle& handle);
  void recv_close(const int32_t seqid);
  void clean(const LogContextId& log_context);
  int32_t send_clean(const LogContextId& log_context);
  void recv_clean(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
