/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ExecStats_TYPES_H
#define ExecStats_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>
#include "Status_types.h"
#include "Types_types.h"


namespace impala {

struct TExecState {
  enum type {
    REGISTERED = 0,
    PLANNING = 1,
    QUEUED = 2,
    RUNNING = 3,
    FINISHED = 4,
    CANCELLED = 5,
    FAILED = 6
  };
};

extern const std::map<int, const char*> _TExecState_VALUES_TO_NAMES;

class TExecStats;

class TPlanNodeExecSummary;

class TExecProgress;

class TExecSummary;

typedef struct _TExecStats__isset {
  _TExecStats__isset() : latency_ns(false), cpu_time_ns(false), cardinality(false), memory_used(false) {}
  bool latency_ns :1;
  bool cpu_time_ns :1;
  bool cardinality :1;
  bool memory_used :1;
} _TExecStats__isset;

class TExecStats {
 public:

  TExecStats(const TExecStats&);
  TExecStats& operator=(const TExecStats&);
  TExecStats() : latency_ns(0), cpu_time_ns(0), cardinality(0), memory_used(0) {
  }

  virtual ~TExecStats() throw();
  int64_t latency_ns;
  int64_t cpu_time_ns;
  int64_t cardinality;
  int64_t memory_used;

  _TExecStats__isset __isset;

  void __set_latency_ns(const int64_t val);

  void __set_cpu_time_ns(const int64_t val);

  void __set_cardinality(const int64_t val);

  void __set_memory_used(const int64_t val);

  bool operator == (const TExecStats & rhs) const
  {
    if (__isset.latency_ns != rhs.__isset.latency_ns)
      return false;
    else if (__isset.latency_ns && !(latency_ns == rhs.latency_ns))
      return false;
    if (__isset.cpu_time_ns != rhs.__isset.cpu_time_ns)
      return false;
    else if (__isset.cpu_time_ns && !(cpu_time_ns == rhs.cpu_time_ns))
      return false;
    if (__isset.cardinality != rhs.__isset.cardinality)
      return false;
    else if (__isset.cardinality && !(cardinality == rhs.cardinality))
      return false;
    if (__isset.memory_used != rhs.__isset.memory_used)
      return false;
    else if (__isset.memory_used && !(memory_used == rhs.memory_used))
      return false;
    return true;
  }
  bool operator != (const TExecStats &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TExecStats & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TExecStats &a, TExecStats &b);

inline std::ostream& operator<<(std::ostream& out, const TExecStats& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TPlanNodeExecSummary__isset {
  _TPlanNodeExecSummary__isset() : label_detail(false), estimated_stats(false), exec_stats(false), is_active(false), is_broadcast(false) {}
  bool label_detail :1;
  bool estimated_stats :1;
  bool exec_stats :1;
  bool is_active :1;
  bool is_broadcast :1;
} _TPlanNodeExecSummary__isset;

class TPlanNodeExecSummary {
 public:

  TPlanNodeExecSummary(const TPlanNodeExecSummary&);
  TPlanNodeExecSummary& operator=(const TPlanNodeExecSummary&);
  TPlanNodeExecSummary() : node_id(0), fragment_id(0), label(), label_detail(), num_children(0), is_broadcast(0) {
  }

  virtual ~TPlanNodeExecSummary() throw();
   ::impala::TPlanNodeId node_id;
  int32_t fragment_id;
  std::string label;
  std::string label_detail;
  int32_t num_children;
  TExecStats estimated_stats;
  std::vector<TExecStats>  exec_stats;
  std::vector<bool>  is_active;
  bool is_broadcast;

  _TPlanNodeExecSummary__isset __isset;

  void __set_node_id(const  ::impala::TPlanNodeId val);

  void __set_fragment_id(const int32_t val);

  void __set_label(const std::string& val);

  void __set_label_detail(const std::string& val);

  void __set_num_children(const int32_t val);

  void __set_estimated_stats(const TExecStats& val);

  void __set_exec_stats(const std::vector<TExecStats> & val);

  void __set_is_active(const std::vector<bool> & val);

  void __set_is_broadcast(const bool val);

  bool operator == (const TPlanNodeExecSummary & rhs) const
  {
    if (!(node_id == rhs.node_id))
      return false;
    if (!(fragment_id == rhs.fragment_id))
      return false;
    if (!(label == rhs.label))
      return false;
    if (__isset.label_detail != rhs.__isset.label_detail)
      return false;
    else if (__isset.label_detail && !(label_detail == rhs.label_detail))
      return false;
    if (!(num_children == rhs.num_children))
      return false;
    if (__isset.estimated_stats != rhs.__isset.estimated_stats)
      return false;
    else if (__isset.estimated_stats && !(estimated_stats == rhs.estimated_stats))
      return false;
    if (__isset.exec_stats != rhs.__isset.exec_stats)
      return false;
    else if (__isset.exec_stats && !(exec_stats == rhs.exec_stats))
      return false;
    if (__isset.is_active != rhs.__isset.is_active)
      return false;
    else if (__isset.is_active && !(is_active == rhs.is_active))
      return false;
    if (__isset.is_broadcast != rhs.__isset.is_broadcast)
      return false;
    else if (__isset.is_broadcast && !(is_broadcast == rhs.is_broadcast))
      return false;
    return true;
  }
  bool operator != (const TPlanNodeExecSummary &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPlanNodeExecSummary & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPlanNodeExecSummary &a, TPlanNodeExecSummary &b);

inline std::ostream& operator<<(std::ostream& out, const TPlanNodeExecSummary& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TExecProgress__isset {
  _TExecProgress__isset() : total_scan_ranges(false), num_completed_scan_ranges(false) {}
  bool total_scan_ranges :1;
  bool num_completed_scan_ranges :1;
} _TExecProgress__isset;

class TExecProgress {
 public:

  TExecProgress(const TExecProgress&);
  TExecProgress& operator=(const TExecProgress&);
  TExecProgress() : total_scan_ranges(0), num_completed_scan_ranges(0) {
  }

  virtual ~TExecProgress() throw();
  int64_t total_scan_ranges;
  int64_t num_completed_scan_ranges;

  _TExecProgress__isset __isset;

  void __set_total_scan_ranges(const int64_t val);

  void __set_num_completed_scan_ranges(const int64_t val);

  bool operator == (const TExecProgress & rhs) const
  {
    if (__isset.total_scan_ranges != rhs.__isset.total_scan_ranges)
      return false;
    else if (__isset.total_scan_ranges && !(total_scan_ranges == rhs.total_scan_ranges))
      return false;
    if (__isset.num_completed_scan_ranges != rhs.__isset.num_completed_scan_ranges)
      return false;
    else if (__isset.num_completed_scan_ranges && !(num_completed_scan_ranges == rhs.num_completed_scan_ranges))
      return false;
    return true;
  }
  bool operator != (const TExecProgress &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TExecProgress & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TExecProgress &a, TExecProgress &b);

inline std::ostream& operator<<(std::ostream& out, const TExecProgress& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TExecSummary__isset {
  _TExecSummary__isset() : status(false), nodes(false), exch_to_sender_map(false), error_logs(false), progress(false) {}
  bool status :1;
  bool nodes :1;
  bool exch_to_sender_map :1;
  bool error_logs :1;
  bool progress :1;
} _TExecSummary__isset;

class TExecSummary {
 public:

  TExecSummary(const TExecSummary&);
  TExecSummary& operator=(const TExecSummary&);
  TExecSummary() : state((TExecState::type)0) {
  }

  virtual ~TExecSummary() throw();
  TExecState::type state;
   ::impala::TStatus status;
  std::vector<TPlanNodeExecSummary>  nodes;
  std::map<int32_t, int32_t>  exch_to_sender_map;
  std::vector<std::string>  error_logs;
  TExecProgress progress;

  _TExecSummary__isset __isset;

  void __set_state(const TExecState::type val);

  void __set_status(const  ::impala::TStatus& val);

  void __set_nodes(const std::vector<TPlanNodeExecSummary> & val);

  void __set_exch_to_sender_map(const std::map<int32_t, int32_t> & val);

  void __set_error_logs(const std::vector<std::string> & val);

  void __set_progress(const TExecProgress& val);

  bool operator == (const TExecSummary & rhs) const
  {
    if (!(state == rhs.state))
      return false;
    if (__isset.status != rhs.__isset.status)
      return false;
    else if (__isset.status && !(status == rhs.status))
      return false;
    if (__isset.nodes != rhs.__isset.nodes)
      return false;
    else if (__isset.nodes && !(nodes == rhs.nodes))
      return false;
    if (__isset.exch_to_sender_map != rhs.__isset.exch_to_sender_map)
      return false;
    else if (__isset.exch_to_sender_map && !(exch_to_sender_map == rhs.exch_to_sender_map))
      return false;
    if (__isset.error_logs != rhs.__isset.error_logs)
      return false;
    else if (__isset.error_logs && !(error_logs == rhs.error_logs))
      return false;
    if (__isset.progress != rhs.__isset.progress)
      return false;
    else if (__isset.progress && !(progress == rhs.progress))
      return false;
    return true;
  }
  bool operator != (const TExecSummary &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TExecSummary & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TExecSummary &a, TExecSummary &b);

inline std::ostream& operator<<(std::ostream& out, const TExecSummary& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
