/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ExecStats_CONSTANTS_H
#define ExecStats_CONSTANTS_H

#include "ExecStats_types.h"

namespace impala {

class ExecStatsConstants {
 public:
  ExecStatsConstants();

};

extern const ExecStatsConstants g_ExecStats_constants;

} // namespace

#endif
