/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ExecStats_constants.h"

namespace impala {

const ExecStatsConstants g_ExecStats_constants;

ExecStatsConstants::ExecStatsConstants() {
}

} // namespace

