/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ImpalaService_constants.h"

namespace impala {

const ImpalaServiceConstants g_ImpalaService_constants;

ImpalaServiceConstants::ImpalaServiceConstants() {
}

} // namespace

