/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImpalaService_CONSTANTS_H
#define ImpalaService_CONSTANTS_H

#include "ImpalaService_types.h"

namespace impala {

class ImpalaServiceConstants {
 public:
  ImpalaServiceConstants();

};

extern const ImpalaServiceConstants g_ImpalaService_constants;

} // namespace

#endif
