/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Status_constants.h"

namespace impala {

const StatusConstants g_Status_constants;

StatusConstants::StatusConstants() {
}

} // namespace

